---
title: "Vaughn et al 2020 Data Vis"
author: "Coastal Carbon Network"
date: "2023-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

## Prepare Workspace ####

library(tidyverse)

# read data
# cores <- read_csv("https://raw.githubusercontent.com/Smithsonian/CCRCN-Data-Library/main/data/CCRCN_synthesis/CCRCN_cores.csv")
depthseries <- read_csv("https://raw.githubusercontent.com/Smithsonian/CCRCN-Data-Library/main/data/CCRCN_synthesis/CCRCN_depthseries.csv")
```

## Excess Pb-210 Depth Profile

```{r pb210, fig.height=12, fig.width=12}

vaughn_ds <- depthseries %>%
  filter(study_id == "Vaughn_et_al_2020") %>% 
  drop_na(excess_pb210_activity) 
  
ggplot(vaughn_ds, aes(x = depth_min, y = excess_pb210_activity)) +    
  geom_line() +    
  geom_point(size = 2, pch=21, fill="white") +    
  facet_wrap(~core_id) +    
  scale_x_reverse() +    
  ylab("Excess Pb-210 Activity (dpm/g)") + xlab("Depth (cm)") +    
  coord_flip() + theme_bw(base_size = 15)

```

```{r}
# library(DT)

knitr::kable(vaughn_ds %>% group_by(core_id) %>% 
               summarize(xs_pb210_min = min(excess_pb210_activity, na.rm = T),
                         xs_pb210_max = max(excess_pb210_activity, na.rm = T)),
             caption = "Ranges of Excess Pb210 Activities within each Core")

```

