---
title: "US Blue Carbon Data Inventory"
author: "Coastal Carbon Network"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme: spacelab
    highlight: tango
---

```{r setup, include=FALSE}
# this sets the working directory to start where the R project is located
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# no warnings or messages
# knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# load libraries
library(tidyverse)
library(sf)
library(rnaturalearth)
```

```{r inventory, echo=FALSE, warning=FALSE, message=FALSE}

# source inventorying functions
source("database_inventory/scripts/inventory_functions.R")

# Import Core Data
cores_v1 <- read_csv("database_inventory/data/synthesis/v1/CONUS_cores.csv", guess_max = 7000)
cores_v2 <- sourceSynthesis()
```

## Report Card Scores

### First Iteration

```{r v1-report, echo=FALSE, warning=FALSE, message=FALSE, fig.height=12, fig.width=12, eval=FALSE}

# inventory the data and compute metrics
scores_v1 <- compositeMetricScore(cores_v1)

## Create Report Card Figure

ggplot(scores_v1, aes(y = metric, x = state)) +
  geom_raster(aes(fill = as.character(normalized_rank))) +
  scale_fill_brewer(palette = "RdYlBu", direction = - 1,
                    labels = c("Best", "", "", "Fair", "", "", "Poor", "No Data")) +
  geom_hline(aes(yintercept = 1.5), size = 1) +
  ylab(NULL) +
  xlab(NULL) +
  coord_flip() +
  # theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust=1, size = 12),
        legend.title = element_blank()) +
  ggtitle("State-Level Blue Carbon Data Report Card")

# extract the fill colors used by ggplot
# g <- ggplot_build(plot)
# unique(g$data[[1]]["fill"])

# ggsave("figures/blue_carbon_report_card.jpg", width=5, height=5, dpi=300)


# ggsave("figures/report_card_variation.jpg")

```

```{r fig.height=12, fig.width=12}
## Alternative Score Card ####

state_rank <- scores_v1 %>%
  filter(metric == "Total") %>%
  mutate(normalized_rank = ifelse(is.na(normalized_rank), 5, normalized_rank)) %>%
  arrange(-normalized_rank)

scores_v1 %>%
  mutate(metric = factor(metric, c("Total", "Quantity", "Quality", "Spatial coverage", "Habitat coverage"))) %>%
  mutate(state = factor(state, state_rank$state)) %>%
  mutate(normalized_rank = as.character(normalized_rank)) %>%
  ggplot(aes(metric, state, fill = normalized_rank)) +
  geom_tile(color = "white", size = 0.5) +
  # coord_equal() +
  # geom_hline(aes(yintercept = 6.5), size = 0.5, col = "grey") +
  # geom_hline(aes(yintercept = 9.5), size = 0.5, col = "grey") +
  # geom_hline(aes(yintercept = 17.5), size = 0.5, col = "grey") +
  # geom_hline(aes(yintercept = 21.5), size = 0.5, col = "grey") +
  geom_vline(aes(xintercept = 1.5), size = 0.5, col = "black") +
  ylab(NULL) + xlab(NULL) +
  scale_fill_brewer(palette = "RdYlBu", direction = -1,
                    labels = c("Best", "", "", "Fair", "", "", "Poor", "No Data")) +
  # facet_wrap(vars(metric)) +
  theme_bw(base_size = 20) +
  theme(legend.title = element_blank(),
    # axis.text.x = element_text(angle = 90),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) +
   ggtitle("State-Level Blue Carbon Data Report Card (Version 1)")

```


### Second Iteration

```{r v2-report, echo=FALSE, warning=FALSE, message=FALSE, fig.height=12, fig.width=12, eval=FALSE}


# inventory the data and compute metrics
scores_v2 <- compositeMetricScore(cores_v2)

## Create Report Card Figure ####

ggplot(scores_v2, aes(y = metric, x = state)) +
  geom_raster(aes(fill = as.character(normalized_rank))) +
  scale_fill_brewer(palette = "RdYlBu", direction = - 1,
                    labels = c("Best", "", "", "Fair", "", "", "Poor", "No Data")) +
  geom_hline(aes(yintercept = 1.5), size = 1) +
  ylab(NULL) +
  xlab(NULL) +
  coord_flip() +
  # theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust=1, size = 12),
        legend.title = element_blank()) +
  ggtitle("State-Level Blue Carbon Data Report Card")

```

```{r fig.height=12, fig.width=12}
## Alternative Score Card ####

state_rank2 <- scores_v2 %>%
  filter(metric == "Total") %>%
  mutate(normalized_rank = ifelse(is.na(normalized_rank), 5, normalized_rank)) %>%
  arrange(-normalized_rank)

scores_v2 %>%
  mutate(metric = factor(metric, c("Total", "Quantity", "Quality", "Spatial coverage", "Habitat coverage"))) %>%
  mutate(state = factor(state, state_rank2$state)) %>%
  mutate(normalized_rank = as.character(normalized_rank)) %>%
  ggplot(aes(metric, state, fill = normalized_rank)) +
  geom_tile(color = "white", size = 0.5) +
  # coord_equal() +
  # geom_hline(aes(yintercept = 6.5), size = 0.5, col = "grey") +
  # geom_hline(aes(yintercept = 9.5), size = 0.5, col = "grey") +
  # geom_hline(aes(yintercept = 17.5), size = 0.5, col = "grey") +
  # geom_hline(aes(yintercept = 21.5), size = 0.5, col = "grey") +
  geom_vline(aes(xintercept = 1.5), size = 0.5, col = "black") +
  ylab(NULL) + xlab(NULL) +
  scale_fill_brewer(palette = "RdYlBu", direction = -1,
                    labels = c("Best", "", "", "Fair", "", "", "Poor", "No Data")) +
  # facet_wrap(vars(metric)) +
  theme_bw(base_size = 20) +
  theme(legend.title = element_blank(),
        # axis.text.x = element_text(angle = 90),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) +
   ggtitle("State-Level Blue Carbon Data Report Card (Version 2)")

```

## Data Inventory Change

```{r comparison, echo=FALSE, warning=FALSE, message=FALSE}
v1 <- read_csv("database_inventory/tables/state_metrics_v1.csv") %>% 
  rename(spatial_metric = spatial_representativeness_metric)

v2 <- read_csv("database_inventory/tables/state_metrics_v2.csv") %>% 
  # make this more elegant in the future
  rename(quantity_metric_v2 = quantity_metric,
         quality_metric_v2 = quality_metric,
         spatial_metric_v2 = spatial_representativeness_metric,
         habitat_metric_v2 = habitat_metric)

all_metrics <- full_join(v1, v2) %>% 
  mutate(across(everything(), replace_na, 0)) %>% 
  mutate(quant_diff = quantity_metric_v2 - quantity_metric,
         qual_diff = quality_metric_v2 - quality_metric,
         spatial_diff = spatial_metric_v2 - spatial_metric, 
         hab_diff = habitat_metric_v2 - habitat_metric)


# eventually create a plotMetricDiffs() fxn

```

### State-Based Overview

```{r state-change, fig.height=12, fig.width=12}
# try a state-based visualization instead

all_metrics_long <- all_metrics %>% 
  select(state, contains("diff")) %>% 
  pivot_longer(cols = -state, names_to = "metric", values_to = "change") %>% 
  mutate(metric = recode(metric, 
                         "spatial_diff" = "Spatial",
                         "quant_diff" = "Quantity",
                         "qual_diff" = "Quality",
                          "hab_diff" = "Habitat"))

all_metrics_long %>% 
  ggplot(aes(metric, change, col = metric)) +
  geom_point(size = 3) +
  geom_segment(aes(xend = metric, yend = 0)) +
  coord_flip() +
  facet_wrap(~state, dir = "v") +
  theme_bw(base_size = 20) +
    theme(legend.position = "bottom")

```

### Metric-Based Overview

```{r metric-change, fig.height=12, fig.width=12}

all_metrics_long %>% 
  ggplot(aes(state, change, col = state)) +
  geom_point(size = 3) +
  geom_segment(aes(xend = state, yend = 0)) +
  coord_flip() +
  facet_wrap(~metric, nrow = 1) +
  theme_bw(base_size = 20) +
  theme(legend.position = "none")
```

### Mapping Change

```{r change-map, echo=FALSE, warning=FALSE, message=FALSE}

# Import states
states <- st_read("database_inventory/data/shapefiles/us_states/states_coastline_boundaries/cb_2017_us_state_500k.shp",
                  stringsAsFactors = F)

# Common projection for states
states_aea <- st_transform(states, crs = "+proj=aea +ellps=WGS84 +lat_1=29.5 +lat_2=45.5 +lon_0=-96 +x_0=0 +y_0=0")

# filter for coastal states
coastal_states <- states_aea %>% 
  # filter(STUSPS %in% unique(all_metrics$state)) %>% 
  rename(state = STUSPS) %>% 
  full_join(all_metrics)

# Continental Boundaries
# map.sf <- ne_countries(scale = 'medium', type = 'map_units', returnclass = 'sf')

# map.na.sf <- map.sf[map.sf$continent == 'North America',]

# map.na.sf.aea <- st_transform(map.na.sf, crs = "+proj=aea +ellps=WGS84 +lat_1=29.5 +lat_2=45.5 +lon_0=-96 +x_0=0 +y_0=0")

## Map States with Composite Scores ####

# generate bounding box

b <- st_bbox(coastal_states %>% filter(state %in% unique(all_metrics$state)))

# ggplot score map
coastal_states %>% 
  ggplot(aes(fill = quant_diff, color = quant_diff)) +
  geom_sf() +
  scale_fill_continuous() +
  scale_color_continuous() +
    # project aes w bounding box
  coord_sf(xlim = c(b["xmin"], b["xmax"]), ylim = c(b["ymin"], b["ymax"]),
           crs="+proj=aea +ellps=WGS84 +lat_1=29.5 +lat_2=45.5 +lon_0=-96 +x_0=0 +y_0=0") +
  # Probably want to take off x and y axes text
  theme_minimal() +
  ggtitle("Change in the Quantity of Available Blue Carbon Data") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  
```


<!-- ### Quantity -->

```{r eval=FALSE}
all_metrics %>% 
  mutate(state = fct_reorder(state, quant_diff)) %>% 
  ggplot(aes(state, quant_diff)) +
  geom_point() +
  geom_segment(aes(xend = state, yend = 0)) + coord_flip() +
    theme_bw(base_size = 15)
# states with no change in quantity should not have change in the other metrics...

```
<!-- ### Quality -->

```{r eval=FALSE}

all_metrics %>% 
  mutate(state = fct_reorder(state, qual_diff)) %>% 
  ggplot(aes(state, qual_diff)) +
  geom_point() +
  geom_segment(aes(xend = state, yend = 0)) + coord_flip() +
    theme_bw(base_size = 15)
```

<!-- ### Spatial Representativeness -->

```{r eval=FALSE}
all_metrics %>% 
  mutate(state = fct_reorder(state, spatial_diff)) %>% 
  ggplot(aes(state, spatial_diff)) +
  geom_point() +
  geom_segment(aes(xend = state, yend = 0)) + coord_flip() +
    theme_bw(base_size = 15)
# negative means the sampling became more clustered
# positive means it became more well-dispersed
```

<!-- ### Habitat Representativeness -->

```{r eval=FALSE}
all_metrics %>% 
  mutate(state = fct_reorder(state, hab_diff)) %>% 
  ggplot(aes(state, hab_diff)) +
  geom_point() +
  geom_segment(aes(xend = state, yend = 0)) + coord_flip() +
    theme_bw(base_size = 15)
```


